# Don't print a new line at the start of the prompt
add_newline = true
command_timeout = 5000

format = """\
    $time\
    $username\
    $hostname\
    $shlvl\
    $directory\
    $vcsh\
    $git_branch\
    $git_commit\
    $git_state\
    $git_metrics\
    $git_status\
    $hg_branch\
    $docker_context\
    $package\
    $cmake\
    $dart\
    $deno\
    $dotnet\
    $elixir\
    $elm\
    $erlang\
    $golang\
    $helm\
    $java\
    $julia\
    $kotlin\
    $nim\
    $nodejs\
    $ocaml\
    $perl\
    $php\
    $purescript\
    $python\
    $red\
    $ruby\
    $rust\
    $scala\
    $swift\
    $terraform\
    $vlang\
    $vagrant\
    $zig\
    $nix_shell\
    $conda\
    $memory_usage\
    $aws\
    $kubernetes\
    $gcloud\
    $openstack\
    $env_var\
    $crystal\
    $custom\
    $cmd_duration\
    $line_break\
    $lua\
    $jobs\
    $battery\
    $status\
    $shell\
    $character\
"""

[kubernetes]
format = '[$symbol$context$symbol]($style)'
disabled = false
contexts = [
  { context_pattern = "^DEV-.+", style = "bold green", symbol = " "},
  { context_pattern = "^PRE-.+", style = "bold fg:220", symbol = " "},
  { context_pattern = "^PROD-.+", style = "bold red bg:white", symbol = " âš ï¸  " },
]

[aws]
# format = 'on [$profile \($symbol $duration\)]($style)'
format = 'on [$profile $symbol]($style)'
symbol = "â˜ï¸ "
style = "bold fg:208"
expiration_symbol="ğŸ’¤"
[aws.region_aliases]
us-east-1 = "N. Virginia"
us-east-2 = "Ohio"
us-west-1 = "N. California"
us-west-2 = "Oregon"
ap-south-1 = "Mumbai"
ap-northeast-1 = "Tokio"
ap-northeast-2 = "Seul"
ap-northeast-3 = "Osaka"
ap-southeast-1 = "Singapur"
ap-southeast-2 = "Sidney"
ca-central-1 = "Canada"
eu-central-1 = "Frankfurt"
eu-central-2 = "Zurich"
eu-west-1 = "Ireland"
eu-west-2 = "Londres"
eu-west-3 = "Paris"
eu-north-1 = "Stockholm"
eu-south-1 = "Milan"
me-central-1 = "AEU"
me-south-1 = "Bahrain"
sa-east-1 = "SÃ£o Paulo"

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

#[[battery.display]]  # "bold green" style when capacity is between 30% and 100%
#threshold = 100
#style = "bold green"

[character]
success_symbol = "[Î»](bold green)"
error_symbol = "[âœ—](bold red)"

[directory]
format = "[$read_only]($read_only_style) [$path]($style) "
style = "bold cyan"
read_only = "ï ½"
read_only_style = "red"
truncation_length = 8
disabled = false

[directory.substitutions]
"~/workspace/personal/GitHub" = "github.com"
"~/workspace/personal/GitLab" = "gitlab.com"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = "ï„¦ " #"ğŸŒ± "
truncation_length = 40
style = "bold purple"

[git_commit]
only_detached = false
commit_hash_length = 7
format = "[ï $hash]($style)"
style = "bold purple"
tag_disabled = false
tag_symbol = "ï€« "

[git_status]
conflicted = "[ï™ $count](bold yellow)"
ahead = "[ïƒ® $count](bold yellow)"
behind = "[ïƒ­ $count](bold red)"
diverged = "[ï¥ $ahead_count-$behind_count](bold red)"
untracked = "[â€¢$count](bold blue)"
stashed = "[ï€œ $count](bold fg:49)"
modified = "[â€¢$count](bold yellow)"
staged = "[â€¢++$count](bold green)"
renamed = "[ï€ $count](bold blue)"
deleted = "[â€¢$count](bold red)"
style = "bold black"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[CHERRY-PICKING ğŸ’](bold red)"
revert = "[REVERTING âªï¸](bold yellow)"
merge = "[MERGING ğŸ”€](bold yellow)"
rebase = "[REBASING ğŸ”€](bold yellow)"

[nodejs]
format = '[$symbol($version )]($style)'
symbol = "â¬¢ "

[java]
format = "[$symbol$version]($style) "
style = "red"

[package]
format = '[$symbol$version]($style) '
style = "bold red"

[python]
style = "bold yellow"
format = "via [${symbol}${pyenv_prefix}(${version} )(\\[$virtualenv\\]) ]($style)"

[docker_context]
disabled = true
style = "blue bold"
only_with_files = true
symbol = "ğŸ³ "
format = "[$symbol]($style) "

[time]
disabled = false
format = "[$time]($style)"
time_format = "%T"

